CREATE DATABASE IF NOT EXISTS `SERVIZIO` ;

use `SERVIZIO`;

CREATE TABLE `compagnia` (
  `NOME` varchar(45) NOT NULL,
  PRIMARY KEY (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `itinerari` (
  `NOME` varchar(45) NOT NULL,
  PRIMARY KEY (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tratte` (
  `NUMTRATTA` int(11) NOT NULL,
  `ITINERARI_NOME` varchar(45) NOT NULL,
  `STAZIONE1` varchar(45) NOT NULL,
  `STAZIONE2` varchar(45) NOT NULL,
  `DURATA` int(11) NOT NULL,
  `LUNGHEZZA` int(11) NOT NULL,
  PRIMARY KEY (`NUMTRATTA`,`ITINERARI_NOME`),
  KEY `ITINERARI_NOME` (`ITINERARI_NOME`),
  CONSTRAINT `tratte_ibfk_1` FOREIGN KEY (`ITINERARI_NOME`) REFERENCES `itinerari` (`NOME`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `treno` (
  `CODTRENO` varchar(45) NOT NULL,
  `COMPAGNIA_NOME` varchar(45) NOT NULL,
  PRIMARY KEY (`CODTRENO`),
  KEY `COMPAGNIA_NOME` (`COMPAGNIA_NOME`),
  CONSTRAINT `treno_ibfk_1` FOREIGN KEY (`COMPAGNIA_NOME`) REFERENCES `compagnia` (`NOME`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `vagone` (
  `NUMVAG` int(11) NOT NULL,
  `CODTRENO` varchar(45) NOT NULL,
  `TIPOLOGIA` varchar(45) NOT NULL,
  `NUMPOSTI` int(11) NOT NULL,
  PRIMARY KEY (`NUMVAG`,`CODTRENO`),
  KEY `CODTRENO` (`CODTRENO`),
  CONSTRAINT `vagone_ibfk_1` FOREIGN KEY (`CODTRENO`) REFERENCES `treno` (`CODTRENO`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `prezzi` (
  `COMPAGNIA_NOME` varchar(45) NOT NULL,
  `TIPOLOGIA` varchar(45) NOT NULL,
  `PREZZO` double NOT NULL,
  PRIMARY KEY (`COMPAGNIA_NOME`,`TIPOLOGIA`),
  CONSTRAINT `prezzi_ibfk_1` FOREIGN KEY (`COMPAGNIA_NOME`) REFERENCES `compagnia` (`NOME`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `viaggio` (
  `CODVIAGGIO` varchar(45) NOT NULL,
  `COMPAGNIA_NOME` varchar(45) NOT NULL,
  `TRENO_CODTRENO` varchar(45) NOT NULL,
  `ITINERARI_NOME` varchar(45) NOT NULL,
  `MODALITA` varchar(45) NOT NULL,
  `DATA_ORA` datetime NOT NULL,
  PRIMARY KEY (`CODVIAGGIO`),
  KEY `COMPAGNIA_NOME` (`COMPAGNIA_NOME`),
  KEY `TRENO_CODTRENO` (`TRENO_CODTRENO`),
  KEY `ITINERARI_NOME` (`ITINERARI_NOME`),
  CONSTRAINT `viaggio_ibfk_1` FOREIGN KEY (`COMPAGNIA_NOME`) REFERENCES `compagnia` (`NOME`) ON UPDATE CASCADE,
  CONSTRAINT `viaggio_ibfk_2` FOREIGN KEY (`TRENO_CODTRENO`) REFERENCES `treno` (`CODTRENO`) ON UPDATE CASCADE,
  CONSTRAINT `viaggio_ibfk_3` FOREIGN KEY (`ITINERARI_NOME`) REFERENCES `itinerari` (`NOME`) ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `registro` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODVIAGGIO` varchar(45) NOT NULL,
  `POSTO` varchar(45) NOT NULL,
  `STAZIONEP` varchar(45) NOT NULL,
  `STAZIONEA` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`,`CODVIAGGIO`),
  KEY `CODVIAGGIO` (`CODVIAGGIO`),
  CONSTRAINT `registro_ibfk_1` FOREIGN KEY (`CODVIAGGIO`) REFERENCES `viaggio` (`CODVIAGGIO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;


